### ISSUE TITLE
Messageをpublishすると稀にクラッシュする

### ISSUE THREAD

**Issue by yutatanamoto** [yutatanamoto/ios-mobile-client#31]
@Acceslayer.swift,  line194
```
transactions[k] = transactions[k] ?? Transaction()
```

のところでたまにクラッシュする。とてもあかん。

**Comment by okappi0258** [comment]
開発者に質問してみたら直してくれました

'''
mutex.sync {
                transactions[k] = transactions[k] ?? Transaction()
                
                // NOTE: The code below MUST use "transactions[k]!...." (instead of a temporary let
                //       as Transaction is a struct and creating temporary variable would make a copy
                //       of it instead of modifying the original object. The methods below are mutable.
                
                // Should the last transaction be continued?
                if retransmit || tranactionMessage.continueTransaction, transactions[k]!.isActive {
                    tranactionMessage.tid = transactions[k]!.currentTid()
                } else {
                    // If not, start a new transaction by setting a new TID value.
                    tranactionMessage.tid = transactions[k]!.nextTid()
                }
            }
'''
mutexで包んだらしいのですが、なぜこれで治ったのかはあまりわからず。
とりあえずこれがこれが原因でクラッシュすることはなくなったので、解決。
