### ISSUE TITLE
Exerciseのタイムプロトコルに合わせてServer制御

### ISSUE THREAD

**Issue by yutatanamoto** [yutatanamoto/ios-mobile-client#42]
- [ ] Phaseが切り替わるタイミングでMeshMessage送信
  - [ ] MeshMessageの送信方法どうするか決定
    - Group宛に送信
    - Node宛に送信

**Comment by yutatanamoto** [comment]
**課題**
- [ ] 順番にNodeの制御を行うと時間がかかる
- [ ] 1.25×Node数[sec.]くらい
- [ ] Nodeは10個あったら12.5秒かかる
- [ ] かなりまずいので高速化する
- [ ] 複数のNodeをより少ないMeshMessageのやりとりで完遂する
- [ ] Group制御か
- [ ] MeshMessageのやりとりに失敗することがある
- [ ] 送信はできてる
- [ ] Node側の受信ができてない
- [ ] 原因調べる

**Comment by okappi0258** [comment]
とりあえず解決案1を採用
LEDごとにcolorcodeの分岐を変えることでそれぞれの練習メニューの phaseのパターンに合わせた
グループ制御はできてるので遅延問題は一応解決
まだ改善する必要がありそうですが、とりあえずcloseします
