### ISSUE TITLE
Node群を制御するのに時間がかかる

### ISSUE THREAD

**Issue by yutatanamoto** [yutatanamoto/ios-mobile-client#44]
**現状の課題**
- 全Nodeを制御し終わるまでに時間がかかる
- 1個のNodeの色を変えるのにかかる時間→1.2秒, 10個Nodeがあれば12秒

**現在のNode群制御方法**
- 各Node内に赤(R)LEDのElement, 青(B)LEDのElement, 緑(G)LEDのElement
- 各Elementに対して, On/OffのMessage(命令)を送信してNodeの色を制御
  - つまり, 1つのNodeの色を変えるために3つのMessageを送信
- Messageの送信を同期的に実行

**解決案1 -Group制御-**
- Group機能を使って, 1回のMessage送信で複数Nodeを制御

**解決案2 -ClientElementの同時複数使用-**
- 制御対象となるServerElementの数と同じだけClientElementを用意しておく
- 同時に複数のClientElementから複数のServerElementに対してMessageを送信

**解決案3 -Nodeに送る情報を1つのMessageに集約-**
- 現状Red, Blue, GreenのLEDを制御するために3つのMessageを送信
- RGBの情報をまとめて1回のMessageのやり取りで完結させる

**Comment by okappi0258** [comment]
とりあえず解決案1を採用
LEDごとにcolorcodeの分岐を変えることでそれぞれの練習メニューの phaseのパターンに合わせた
グループ制御はできてるので遅延問題は一応解決
